markdown: rdiscount
permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Jake Kenneally
url: https://jakekenneally.com
description: Personal homepage of software engineer Jake Kenneally
twitter: jakeapher
linkedin: jakekenneally
