markdown: rdiscount
permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Jake Kenneally
url: https://jakekenneally.me
description: Geek. Nerd. Hacker.
twitter: jakeapher
googleplus: +JakeKenneally
linkedin: jakekenneally
