markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Jake Kenneally
url: http://jakekenneally.me
description: Geek. Nerd. Hacker.
twitter: jakeapher
googleplus: +JakeKenneally
linkedin: jakekenneally